Repository SOPT-all/35-COLLABORATION-iOS-DAANGN, pull requests merged in 2024-11, with the labels that each got.

#2 [Setting] #1 - 프로젝트 세팅
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Application/AppDelegate.swift
  Daangn_iOS/Daangn_iOS/Application/SceneDelegate.swift
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/AccentColor.colorset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/AppIcon.appiconset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Base.lproj/LaunchScreen.storyboard
  Daangn_iOS/Daangn_iOS/Global/Literals/StringLiterals.swift
  Daangn_iOS/Daangn_iOS/Info.plist
  Daangn_iOS/Daangn_iOS/Network/BaseResponseModel.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Home/Cells/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Home/Models/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Home/Views/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Product/ViewControllers/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Product/Views/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Profile/Cells/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Profile/Models/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Profile/ViewControllers/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Profile/Views/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Search/Cells/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Search/Models/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Search/ViewControllers/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Search/Views/.gitkeep
  Daangn_iOS/Daangn_iOS/ViewController.swift
Labels: 나연 🥨, 💡 Setting

#5 [Feat] #3 - 폰트 스타일 가이드 설정 및 extension 함수 추가
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Global/Extensions/UIFont+.swift
  Daangn_iOS/Daangn_iOS/Global/Extensions/UILabel+.swift
  Daangn_iOS/Daangn_iOS/Global/Extensions/UIStackView+.swift
  Daangn_iOS/Daangn_iOS/Global/Extensions/UIView+.swift
  Daangn_iOS/Daangn_iOS/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Resources/Assets.xcassets/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Resources/Base.lproj/LaunchScreen.storyboard
Labels: 나연 🥨, ☀️ Feat, 💡 Setting

#8 Feat/#6 create product card view
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Application/SceneDelegate.swift
  Daangn_iOS/Daangn_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Daangn_iOS/Daangn_iOS/Network/DTO/ProductResponseDOT.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/ProductCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 정욱 🥪, ☀️ Feat

#15 [Feat] #9 - ProductDetailCompositionLayout, ProductRelatedCollectionViewCell 구현
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Global/Extensions/ClassNameProtocol.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/KeywordNotifyCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductDetailInfoCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductImageCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductRelatedCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductRelatedHeaderReusableView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/SellerInfoCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/ProductDetailSection.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/ProductRelatedModel.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ProductDetailCompositionalLayout.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ViewControllers/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Product/ViewControllers/ProductDetailViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Views/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Product/Views/ProductDetailView.swift
Labels: 유빈 🍿, ☀️ Feat

#16 [Feat] #10 - 공통 컴포넌트 UI 구현
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/AccentColor.colorset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_direction_left_white.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_direction_left_white.imageset/ic_direction_left_white.svg
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_direction_right_black_lg.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_direction_right_black_lg.imageset/ic_direction_right_black_lg.svg
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_direction_right_black_sm.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_direction_right_black_sm.imageset/ic_direction_right_black_sm.svg
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_home_white.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_home_white.imageset/ic_home_white.svg
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_menu_hamburger.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_menu_hamburger.imageset/ic_menu_hamburger.svg
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_menu_kebab_white.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_menu_kebab_white.imageset/ic_menu_kebab_white.svg
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_notification_lg.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_notification_lg.imageset/ic_notification_lg.svg
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_search.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_search.imageset/ic_search.svg
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_share_white.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_share_white.imageset/ic_share_white.svg
  Daangn_iOS/Daangn_iOS/Global/Extensions/String+.swift
  Daangn_iOS/Daangn_iOS/Global/Extensions/UIFont+.swift
  Daangn_iOS/Daangn_iOS/Global/Literals/StringLiterals.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/DaangnNavigationBar.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/HeaderCollectionReusableView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/ProductCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/TopTabbar.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/TopTabbarCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductRelatedHeaderReusableView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Search/Models/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Search/Models/TopTabbarModel.swift
  Daangn_iOS/Daangn_iOS/Presentation/Search/ViewControllers/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Search/Views/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Search/Views/SearchView.swift
Labels: 나연 🥨, ☀️ Feat

#19 Feat/#11 setting main view layout
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Application/AppDelegate.swift
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_reset.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_reset.imageset/ic_reset (1).svg
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Images/img_reset.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Images/img_reset.imageset/img_reset.png
  Daangn_iOS/Daangn_iOS/Global/Extensions/IntrinsicCollectionView.swift
  Daangn_iOS/Daangn_iOS/Network/DTO/HomeTag.swift
  Daangn_iOS/Daangn_iOS/Network/DTO/ProductResponseDOT.swift
  Daangn_iOS/Daangn_iOS/Network/DTO/ProductResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/DaangnNavigationBar.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/ProductCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/Cells/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Home/Cells/TagCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/Views/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Home/Views/SectionLayout.swift
Labels: 정욱 🥪, ☀️ Feat

#23 Feat/#20 detailed filter view
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Network/DTO/CategoryResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Presentation/DetaileFilter/Cell/FilterListViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/DetaileFilter/ViewControllers/CategoryListViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/DetaileFilter/ViewControllers/DetailFilterViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/DetaileFilter/Views/DetaileFilterView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/Cells/TagCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 정욱 🥪, ☀️ Feat

#25 Feat/#24 create fixed button
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Presentation/DetaileFilter/Cell/FilterListViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/DetaileFilter/ViewControllers/DetailFilterViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/DetaileFilter/Views/DetaileFilterView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/Models/.gitkeep
  Daangn_iOS/Daangn_iOS/Presentation/Home/Models/HomeTag.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 정욱 🥪, ☀️ Feat

#30 Feat/#27 - SellerInfoCollectionViewCell, ProductDetailInfoCollectionViewCell 구현
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductDetailInfoCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/SellerInfoCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/ProductInfoDTO.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/SellerInfoDTO.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ProductDetailCompositionalLayout.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ViewControllers/ProductDetailViewController.swift
Labels: 유빈 🍿, ☀️ Feat

#29 [Setting] #28 - Moya 네트워크 통신 세팅
  Daangn_iOS/Daangn_iOS/Info.plist
  Daangn_iOS/Daangn_iOS/Network/Base/BaseResponseModel.swift
  Daangn_iOS/Daangn_iOS/Network/Base/Config.swift
  Daangn_iOS/Daangn_iOS/Network/Base/MoyaLoggingPlugin.swift
  Daangn_iOS/Daangn_iOS/Network/Base/NetworkResult.swift
  Daangn_iOS/Daangn_iOS/Network/BaseResponseModel.swift
  Daangn_iOS/Daangn_iOS/Network/DTO/CategoryResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Network/DTO/ProductResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Network/Service/DaangnService.swift
  Daangn_iOS/Daangn_iOS/Network/TargetType/HomeTargetType.swift
  Daangn_iOS/Daangn_iOS/Network/TargetType/ProductTargetType.swift
  Daangn_iOS/Daangn_iOS/Network/TargetType/SearchTargetType.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/ProductCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 나연 🥨, ⚡️ Network, 💡 Setting

#34 Feat/#33 KeywordNotifyCell, PurchaseBottomView 구현
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/HeaderCollectionReusableView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/KeywordNotifyCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductRelatedHeaderReusableView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/SellerInfoCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/ProductDetailSection.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ProductDetailCompositionalLayout.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ViewControllers/ProductDetailViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Views/ProductDetailView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Views/PurchaseBottomView.swift
Labels: 유빈 🍿, ☀️ Feat

#43 [Network] #39 - ProductDetail 섹션 API 연동
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Network/DTO/ProductDetailResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Network/DTO/UserInfoResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Network/DTO/UserSellingProductResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Network/Service/DaangnService.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/KeywordNotifyCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductDetailInfoCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductImageCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductRelatedCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/UserInfoCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/ProductDetailSection.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/ProductRelatedModel.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/SellerInfoDTO.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ProductDetailCompositionalLayout.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ViewControllers/ProductDetailViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Views/PurchaseBottomView.swift
Labels: 유빈 🍿, ⚡️ Network

#44 [Feat] [Hotfix] #42 - DTO 변경된 문제 해결 및 하단 탭바 구현
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Application/SceneDelegate.swift
  Daangn_iOS/Daangn_iOS/Global/Assets.xcassets/Icons/ic_bottombar_chat.imageset/Contents.json
  Daangn_iOS/Daangn_iOS/Network/DTO/UserProfileResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Network/Service/DaangnService.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/DaangnNavigationBar.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductImageCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Profile/ViewControllers/ProfileViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/TabBar/DaangnTabBarController.swift
  Daangn_iOS/Daangn_iOS/Presentation/TabBar/DaangnTabBarItem.swift
Labels: 나연 🥨, ☀️ Feat, ❄️ Fix

#40 Feat/#38 상품 목록, 카테고리 목록 API 연결
  Daangn_iOS/Daangn_iOS.xcodeproj/project.pbxproj
  Daangn_iOS/Daangn_iOS/Network/DTO/CategoryResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Network/DTO/CatogoriesResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Network/DTO/ProductResponseDTO.swift
  Daangn_iOS/Daangn_iOS/Network/Service/DaangnService.swift
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/ProductCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/DetailFilter/Cell/CategoryListViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/DetailFilter/ViewControllers/CategoryListViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/DetailFilter/ViewControllers/DetailFilterViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 정욱 🥪, ⚡️ Network

#45 [Feat] #42 - 전체적인 화면 이동 로직 구현
  Daangn_iOS/Daangn_iOS/Presentation/Common/Component/ProductCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/KeywordNotifyCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductDetailInfoCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Cells/ProductRelatedCollectionViewCell.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Models/ProductDetailSection.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ProductDetailCompositionalLayout.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/ViewControllers/ProductDetailViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Product/Views/ProductDetailView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Profile/ViewControllers/ProfileViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Profile/Views/ProfileView.swift
  Daangn_iOS/Daangn_iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  Daangn_iOS/Daangn_iOS/Presentation/Search/ViewControllers/SecondHandTradingViewController.swift
Labels: 나연 🥨, ☀️ Feat, ❄️ Fix
